### ISSUE TITLE
PerfectThread build failed

### ISSUE THREAD

**Issue by ps410** [PerfectlySoft/Perfect-Thread#1]
Can't build the PerfectTemplate because PerfectThread failed on linux.

I'm using Swift 3.0. Maybe I'm doing something wrong....

Compile Swift Module 'PerfectThread' (2 sources)
/vagrant/PerfectTemplate/Packages/PerfectThread-0.5.0/Sources/ThreadQueue.swift:195:74: error: cannot convert value of type 'UnsafeMutablePointer<Void>' (aka 'UnsafeMutablePointer<()>') to expected argument type 'OpaquePointer'
                let unleakyObject = Unmanaged<IsThisRequired>.fromOpaque(pCheck).takeRetainedValue()
                                                                         ^~~~~~
/vagrant/PerfectTemplate/Packages/PerfectThread-0.5.0/Sources/ThreadQueue.swift:200:37: error: value of type 'Unmanaged<Threading.IsThisRequired>' has no member 'toOpaque'
        let leakyObject = Unmanaged.passRetained(holderObject).toOpaque()
                          ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~
<unknown>:0: error: build had 1 command failures

**Comment by taplin** [comment]
You should find that this issue is fixed in the current master.

**Comment by iamjono** [comment]
Closing, please re-open with comment if not fixed in latest commit.
